name: Hello world and Test on Push to Main

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Hello World script
        run: echo "Hello, World!"

      - name: Run tests
        run: npm test