name: Hello World on Push to Main

on:
  push:
    branches:
      - main

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Hello World script
        run: echo "Hello, World!"
