name: unit test on push to main

on:
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install dependencies
        run: npm install --force

      - name: Run tests
        run: npm test
